import type { Params } from './shape-params';

export const shapeDefaults: Record<string, Params> = {
  cylinder: { diameter: 120, height: 140, wallThickness: 6 },
  cube: { width: 120, depth: 120, height: 120, wallThickness: 6 },
  box: {
    width: 160,
    depth: 110,
    height: 90,
    wallThickness: 6,
    hasLid: 0,
    lidStyle: 0,
    lidClearance: 1.5,
    lidLift: 30,
    lidSkirtHeight: 24,
  },
  'truncated-cone': { topDiameter: 90, bottomDiameter: 150, height: 130, wallThickness: 6 },
  vase: {
    topDiameter: 80,
    bottomDiameter: 130,
    height: 200,
    wallThickness: 6,
    hasLid: 0,
    lidStyle: 0,
    lidClearance: 1.5,
    lidLift: 30,
    lidSkirtHeight: 24,
  },
  bowl: {
    topDiameter: 180,
    bottomDiameter: 80,
    height: 90,
    wallThickness: 6,
    hasLid: 0,
    lidStyle: 0,
    lidClearance: 1.5,
    lidLift: 30,
  },
  'oval-box': {
    width: 170,
    depth: 110,
    height: 80,
    roundness: 80,
    wallThickness: 6,
    hasLid: 0,
    lidStyle: 0,
    lidClearance: 1.5,
    lidLift: 30,
    lidSkirtHeight: 24,
  },
  'hexagonal-prism': {
    bottomRadius: 75,
    topRadius: 75,
    height: 140,
    wallThickness: 6,
    includeBase: 6,
    closedTop: 0,
  },
  'octagonal-prism': {
    bottomRadius: 75,
    topRadius: 75,
    height: 140,
    wallThickness: 6,
    includeBase: 6,
    closedTop: 0,
  },
  'tapered-box': {
    bottomWidth: 150,
    bottomDepth: 110,
    topWidth: 125,
    topDepth: 90,
    height: 130,
    wallThickness: 6,
    includeBase: 6,
    closedTop: 0,
  },
  'truncated-square-pyramid': {
    bottomWidth: 150,
    bottomDepth: 150,
    topWidth: 100,
    topDepth: 100,
    height: 130,
    wallThickness: 6,
    includeBase: 6,
    closedTop: 0,
  },
  'polygonal-vase': {
    sides: 8,
    bottomWidth: 90,
    bottomDepth: 90,
    midWidth: 150,
    midDepth: 150,
    topWidth: 80,
    topDepth: 80,
    height: 200,
    rotation: 0,
    wallThickness: 6,
    includeBase: 6,
  },
  'rounded-rectangle-box': {
    width: 160,
    depth: 110,
    cornerRadius: 22,
    points: 24,
    height: 90,
    wallThickness: 6,
    includeBase: 6,
  },
  'elliptical-vase': {
    sides: 16,
    bottomWidth: 90,
    bottomDepth: 70,
    midWidth: 155,
    midDepth: 115,
    topWidth: 80,
    topDepth: 65,
    height: 200,
    rotation: 0,
    wallThickness: 6,
    includeBase: 6,
  },
  'faceted-bowl': {
    bowlDiameter: 180,
    bowlDepth: 90,
    baseDiameter: 65,
    rimDiameter: 180,
    facets: 10,
    wallThickness: 6,
    includeBase: 6,
    hasLid: 0,
    lidStyle: 0,
    lidClearance: 1.5,
    lidLift: 30,
  },
  'gored-sphere': {
    diameter: 180,
    height: 180,
    topOpening: 25,
    bottomOpening: 35,
    gores: 12,
    wallThickness: 6,
    includeBase: 6,
  },
  'teardrop-vessel': {
    sides: 16,
    baseWidth: 48,
    baseDepth: 42,
    bodyWidth: 185,
    bodyDepth: 155,
    topOpening: 22,
    height: 240,
    rotation: 0,
    wallThickness: 6,
    includeBase: 6,
  },
  'organic-lofted-vessel': {
    points: 16,
    bottomWidth: 85,
    bottomDepth: 70,
    midWidth: 160,
    midDepth: 125,
    topWidth: 75,
    topDepth: 90,
    height: 210,
    rotation: 18,
    wallThickness: 6,
    includeBase: 6,
  },
};

